### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by mjuniper** [toranb/ember-cli-auto-complete#33]
I'm a bit confused. NPM (https://www.npmjs.com/package/ember-cli-auto-complete) says this addon is at 0.2.1 and, of course that's what I get when I `npm install ember-cli-auto-complete --save-dev` or `ember install ember-cli-auto-complete`. But npm says that is the latest of 21 releases and this repo says there are no releases and package.json on master says that the current version is 1.0.0-beta.2. Does npm actually point to an old repo or something?

Relatedly, I think the readme reflects stuff that is on master but not on 0.2.1, like `hideWhenNoSuggestions`.

**Comment by toranb** [comment]
The last non beta release was 0.2.1 and we've been working on a beta release (you could install it doing this)

```
npm install ember-cli-auto-complete@1.0.0-beta.2
```

Admittedly I've been slow to ship the official 1.0 release. A large part is that the api went through some legit breaking changes since 0.2.1 (a valid reason to semver this thing up to 1.0.0) but we also have a TON of issues showing up this week from @jamesarosen and I'd like to have this a bit more solid before we jump ahead.

About the README - another developer opened an issue about this and this is a problem. I was hoping he would submit a PR and we could push it back to 0.2.1/and or something for the 1.0.0 beta 2

https://github.com/toranb/ember-cli-auto-complete/issues/29

Would you be interested in using the beta and opening issues/helping polish it up before we ship?

**Comment by toranb** [comment]
**update**

The latest is 1.0.0 beta 3

```
npm install ember-cli-auto-complete@1.0.0-beta.3
```
